### ISSUE TITLE
2.5.2-beta下载下来的工程运行报错

### ISSUE THREAD

**Issue by jpsz01** [aicareles/Android-BLE#18]
java.lang.reflect.UndeclaredThrowableException
at $Proxy3.connect(Unknown Source)
        at cn.com.heaton.blelibrary.ble.Ble.connect(Ble.java:134)

**Comment by ZhanRu** [comment]
一样的错误 Android 9.0

 --------- beginning of crash
2019-03-11 21:48:32.807 10255-10255/com.wmailn.blepen E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.wmailn.blepen, PID: 10255
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.wmailn.blepen/com.wmailn.blepen.ui.pen.BindingPenActivity_}: java.lang.reflect.UndeclaredThrowableException
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3300)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3484)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:86)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2123)
        at android.os.Handler.dispatchMessage(Handler.java:109)
        at android.os.Looper.loop(Looper.java:207)
        at android.app.ActivityThread.main(ActivityThread.java:7470)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)
     Caused by: java.lang.reflect.UndeclaredThrowableException
        at $Proxy3.startScan(Unknown Source)
        at cn.com.heaton.blelibrary.ble.Ble.startScan(Ble.java:108)
        at com.wmailn.blepen.ui.pen.BindingPenActivity.searchDevice(BindingPenActivity.java:180)
        at com.wmailn.blepen.ui.pen.BindingPenActivity.doIsBlueEnable(BindingPenActivity.java:434)
        at com.wmailn.blepen.ui.pen.BindingPenActivity.afterViews(BindingPenActivity.java:97)
        at com.wmailn.blepen.ui.pen.BindingPenActivity_.onViewChanged(BindingPenActivity_.java:81)
        at org.androidannotations.api.view.OnViewChangedNotifier.notifyViewChanged(OnViewChangedNotifier.java:41)
        at com.wmailn.blepen.ui.pen.BindingPenActivity_.setContentView(BindingPenActivity_.java:50)
        at com.wmailn.blepen.ui.pen.BindingPenActivity_.onCreate(BindingPenActivity_.java:35)
        at android.app.Activity.performCreate(Activity.java:7436)
        at android.app.Activity.performCreate(Activity.java:7426)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1286)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3279)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3484) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:86) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2123) 
        at android.os.Handler.dispatchMessage(Handler.java:109) 
        at android.os.Looper.loop(Looper.java:207) 
        at android.app.ActivityThread.main(ActivityThread.java:7470) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958) 
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at cn.com.heaton.blelibrary.ble.proxy.RequestProxy.invoke(RequestProxy.java:50)
        at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
        at $Proxy3.startScan(Unknown Source) 
        at cn.com.heaton.blelibrary.ble.Ble.startScan(Ble.java:108) 
        at com.wmailn.blepen.ui.pen.BindingPenActivity.searchDevice(BindingPenActivity.java:180) 
        at com.wmailn.blepen.ui.pen.BindingPenActivity.doIsBlueEnable(BindingPenActivity.java:434) 
        at com.wmailn.blepen.ui.pen.BindingPenActivity.afterViews(BindingPenActivity.java:97) 
        at com.wmailn.blepen.ui.pen.BindingPenActivity_.onViewChanged(BindingPenActivity_.java:81) 
        at org.androidannotations.api.view.OnViewChangedNotifier.notifyViewChanged(OnViewChangedNotifier.java:41) 
        at com.wmailn.blepen.ui.pen.BindingPenActivity_.setContentView(BindingPenActivity_.java:50) 
        at com.wmailn.blepen.ui.pen.BindingPenActivity_.onCreate(BindingPenActivity_.java:35) 
        at android.app.Activity.performCreate(Activity.java:7436) 
        at android.app.Activity.performCreate(Activity.java:7426) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1286) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3279) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3484) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:86) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2123) 
        at android.os.Handler.dispatchMessage(Handler.java:109) 
        at android.os.Looper.loop(Looper.java:207) 
        at android.app.ActivityThread.main(ActivityThread.java:7470) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958) 
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void cn.com.heaton.blelibrary.ble.request.ScanRequest.startScan(cn.com.heaton.blelibrary.ble.callback.BleScanCallback, int)' on a null object reference
        at cn.com.heaton.blelibrary.ble.proxy.RequestImpl.startScan(RequestImpl.java:33)
        at java.lang.reflect.Method.invoke(Native Method) 
        at cn.com.heaton.blelibrary.ble.proxy.RequestProxy.invoke(RequestProxy.java:50) 
        at java.lang.reflect.Proxy.invoke(Proxy.java:1006) 
        at $Proxy3.startScan(Unknown Source) 
        at cn.com.heaton.blelibrary.ble.Ble.startScan(Ble.java:108) 
        at com.wmailn.blepen.ui.pen.BindingPenActivity.searchDevice(BindingPenActivity.java:180) 
        at com.wmailn.blepen.ui.pen.BindingPenActivity.doIsBlueEnable(BindingPenActivity.java:434) 
        at com.wmailn.blepen.ui.pen.BindingPenActivity.afterViews(BindingPenActivity.java:97) 
        at com.wmailn.blepen.ui.pen.BindingPenActivity_.onViewChanged(BindingPenActivity_.java:81) 
        at org.androidannotations.api.view.OnViewChangedNotifier.notifyViewChanged(OnViewChangedNotifier.java:41) 
        at com.wmailn.blepen.ui.pen.BindingPenActivity_.setContentView(BindingPenActivity_.java:50) 
        at com.wmailn.blepen.ui.pen.BindingPenActivity_.onCreate(BindingPenActivity_.java:35) 
        at android.app.Activity.performCreate(Activity.java:7436) 
        at android.app.Activity.performCreate(Activity.java:7426) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1286) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3279) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3484) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:86) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2123) 
        at android.os.Handler.dispatchMessage(Handler.java:109) 
        at android.os.Looper.loop(Looper.java:207) 
        at android.app.ActivityThread.main(ActivityThread.java:7470) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)

**Comment by ZhanRu** [comment]
经跟群主沟通，2.5.3版本，编译时需关闭 Instant Run

**Comment by MrZhangYang** [comment]
总感觉反射不太好

**Comment by MrZhangYang** [comment]
设计思路很好啊，但是感觉用反射总会出现莫名其妙问题

**Comment by MrZhangYang** [comment]
有的手机即使instant run关闭也是有问题的

log 如下
03-14 18:31:42.428 11383-11383/com.example.admin.mybledemo E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.admin.mybledemo, PID: 11383
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.admin.mybledemo/com.example.admin.mybledemo.activity.BleActivity}: java.lang.reflect.UndeclaredThrowableException
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2423)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2483)
        at android.app.ActivityThread.-wrap11(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1345)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5431)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
     Caused by: java.lang.reflect.UndeclaredThrowableException
        at $Proxy8.startScan(Unknown Source)
        at cn.com.heaton.blelibrary.ble.Ble.startScan(Ble.java:108)
        at com.example.admin.mybledemo.activity.BleActivity.checkBluetoothStatus(BleActivity.java:104)
        at com.example.admin.mybledemo.activity.BleActivity.initBle(BleActivity.java:88)
        at com.example.admin.mybledemo.activity.BleActivity.access$000(BleActivity.java:57)
        at com.example.admin.mybledemo.activity.BleActivity$1.onResult(BleActivity.java:117)
        at com.example.admin.mybledemo.activity.BaseActivity$GrantedResult.run(BaseActivity.java:168)
        at android.app.Activity.runOnUiThread(Activity.java:5524)
        at com.example.admin.mybledemo.activity.BaseActivity.requestPermission(BaseActivity.java:117)
        at com.example.admin.mybledemo.activity.BleActivity.requestPermission(BleActivity.java:110)
        at com.example.admin.mybledemo.activity.BleActivity.onInitView(BleActivity.java:71)
        at com.example.admin.mybledemo.activity.BaseActivity.onCreate(BaseActivity.java:36)
        at android.app.Activity.performCreate(Activity.java:6251)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2376)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2483) 
        at android.app.ActivityThread.-wrap11(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1345) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:148) 
        at android.app.ActivityThread.main(ActivityThread.java:5431) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at cn.com.heaton.blelibrary.ble.proxy.RequestProxy.invoke(RequestProxy.java:50)
        at java.lang.reflect.Proxy.invoke(Proxy.java:393)
        at $Proxy8.startScan(Unknown Source) 
        at cn.com.heaton.blelibrary.ble.Ble.startScan(Ble.java:108) 
        at com.example.admin.mybledemo.activity.BleActivity.checkBluetoothStatus(BleActivity.java:104) 
        at com.example.admin.mybledemo.activity.BleActivity.initBle(BleActivity.java:88) 
        at com.example.admin.mybledemo.activity.BleActivity.access$000(BleActivity.java:57) 
        at com.example.admin.mybledemo.activity.BleActivity$1.onResult(BleActivity.java:117) 
        at com.example.admin.mybledemo.activity.BaseActivity$GrantedResult.run(BaseActivity.java:168) 
        at android.app.Activity.runOnUiThread(Activity.java:5524) 
        at com.example.admin.mybledemo.activity.BaseActivity.requestPermission(BaseActivity.java:117) 
        at com.example.admin.mybledemo.activity.BleActivity.requestPermission(BleActivity.java:110) 
        at com.example.admin.mybledemo.activity.BleActivity.onInitView(BleActivity.java:71) 
        at com.example.admin.mybledemo.activity.BaseActivity.onCreate(BaseActivity.java:36) 
        at android.app.Activity.performCreate(Activity.java:6251) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2376) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2483) 
        at android.app.ActivityThread.-wrap11(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1345) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:148) 
        at android.app.ActivityThread.main(ActivityThread.java:5431) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void cn.com.heaton.blelibrary.ble.request.ScanRequest.startScan(cn.com.heaton.blelibrary.ble.callback.BleScanCallback, int)' on a null object reference
        at cn.com.heaton.blelibrary.ble.proxy.RequestImpl.startScan(RequestImpl.java:33)
        at java.lang.reflect.Method.invoke(Native Method) 
        at cn.com.heaton.blelibrary.ble.proxy.RequestProxy.invoke(RequestProxy.java:50) 
        at java.lang.reflect.Proxy.invoke(Proxy.java:393) 
        at $Proxy8.startScan(Unknown Source) 
        at cn.com.heaton.blelibrary.ble.Ble.startScan(Ble.java:108) 
        at com.example.admin.mybledemo.activity.BleActivity.checkBluetoothStatus(BleActivity.java:104) 
        at com.example.admin.mybledemo.activity.BleActivity.initBle(BleActivity.java:88) 
        at com.example.admin.mybledemo.activity.BleActivity.access$000(BleActivity.java:57) 
        at com.example.admin.mybledemo.activity.BleActivity$1.onResult(BleActivity.java:117) 
        at com.example.admin.mybledemo.activity.BaseActivity$GrantedResult.run(BaseActivity.java:168) 
        at android.app.Activity.runOnUiThread(Activity.java:5524) 
        at com.example.admin.mybledemo.activity.BaseActivity.requestPermission(BaseActivity.java:117) 
        at com.example.admin.mybledemo.activity.BleActivity.requestPermission(BleActivity.java:110) 
        at com.example.admin.mybledemo.activity.BleActivity.onInitView(BleActivity.java:71) 
        at com.example.admin.mybledemo.activity.BaseActivity.onCreate(BaseActivity.java:36) 
        at android.app.Activity.performCreate(Activity.java:6251) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2376) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2483) 
        at android.app.ActivityThread.-wrap11(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1345) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:148) 
        at android.app.ActivityThread.main(ActivityThread.java:5431) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by aicareles** [comment]
最新版本已经解决这个问题,十分感谢你们的提问
