### ISSUE TITLE
java.lang.NoClassDefFoundError: cn.com.heaton.blelibrary.ble.request.AdvertiserRequest$4

### ISSUE THREAD

**Issue by ghost** [aicareles/Android-BLE#29]
java.lang.NoClassDefFoundError: cn.com.heaton.blelibrary.ble.request.AdvertiserRequest$4
        at cn.com.heaton.blelibrary.ble.request.AdvertiserRequest.<init>(AdvertiserRequest.java:95)
        at java.lang.Class.newInstanceImpl(Native Method)
        at java.lang.Class.newInstance(Class.java:1208)
        at cn.com.heaton.blelibrary.ble.request.Rproxy.init(Rproxy.java:44)
        at cn.com.heaton.blelibrary.ble.proxy.RequestProxy.bindProxy(RequestProxy.java:42)
        at cn.com.heaton.blelibrary.ble.Ble.init(Ble.java:96)
        at cn.com.heaton.blelibrary.ble.Ble.create(Ble.java:108)
        at cn.com.heaton.blelibrary.ble.Ble.create(Ble.java:103)
        at cn.com.heaton.blelibrary.ble.Ble$Options.create(Ble.java:806)
        at com.uhf.demo.bluetooth.BleManager.<init>(BleManager.java:78)
        at com.uhf.demo.bluetooth.BleManager.from(BleManager.java:56)
        at com.uhf.demo.connect.ConnectActivity.initData(ConnectActivity.java:124)
        at com.uhf.demo.base.BaseActivity.onCreate(BaseActivity.java:89)
        at android.app.Activity.performCreate(Activity.java:5274)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2151)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2236)
        at android.app.ActivityThread.access$800(ActivityThread.java:138)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1199)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:5095)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:602)
        at dalvik.system.NativeStart.main(Native Method)

**Comment by aicareles** [comment]
什么机型和系统版本
