### ISSUE TITLE
Caused by: java.lang.reflect.UndeclaredThrowableException 

### ISSUE THREAD

**Issue by chenni521** [aicareles/Android-BLE#92]
Caused by: java.lang.reflect.UndeclaredThrowableException
        at $Proxy2.startScan(Unknown Source)
        at cn.com.heaton.blelibrary.ble.Ble.startScan(Ble.java:157)
        at com.swaddling.home.view.BluetoothActivity.requestPermission(BluetoothActivity.java:229)
        at com.swaddling.home.view.BluetoothActivity.initData(BluetoothActivity.java:112)

![}TMI24KPZWW MFMWM I5 PH](https://user-images.githubusercontent.com/13419194/131607957-633c17a6-fff1-4cdb-8441-7deb90205058.png)

**Comment by Waterelone** [comment]
请问你是怎么解决的啊

**Comment by Waterelone** [comment]
我也遇到了这个问题

**Comment by chenni521** [comment]
我也不知道
